# Generated by Django 6.0.6 on 2026-06-17 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(blank=True, max_length=200)),
                ('wip_limit', models.PositiveSmallIntegerField(default=3)),
                ('pomodoro_work_minutes', models.PositiveSmallIntegerField(default=25)),
                ('pomodoro_break_minutes', models.PositiveSmallIntegerField(default=5)),
                ('pomodoro_long_break_minutes', models.PositiveSmallIntegerField(default=15)),
                ('pomodoro_cycles_before_long_break', models.PositiveSmallIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
